export const skills = [
  "Semantic & accessible HTML",
  "React",
  "Promises, Async/Await",
  "Responsive Web Design",
  "React Router",
  "GitHub Pull Requests & Review",
  "JavaScript: ES6+",
  "React Hooks",
  "Trello",
  "Markdown",
  "Redux (Toolkit)",
  "Scrum",
  "Immutability",
  "Error handling",
  "NPM",
  "CSS BEM convention",
  "Working with API (fetch, axios)",
  "Teamwork",
  "CSS Grid",
  "Redux-Saga",
  "Git",
  "CSS Flexbox",
  "Database operations",
  "Experience with Streamsoft",
  "Knowledge of the MS Office suite (Power Query, administrative panel)",
];

export const skillsToLearn = [
  "TypeScript",
  "C#",
  "Java",
];